export enum LobbyEvents {
    Create = 'create',
    CreateSoloSprint = 'createSoloSprint',
    CreateMultiplayerSprint = 'createMultiplayerSprint',
    StartSolo = 'startSolo',
    Join = 'join',
    Wait = 'wait',
    StatusChanged = 'statusChanged',
    RequestToJoin = 'requestToJoin',
    Accepted = 'accepted',
    Reject = 'reject',
    Left = 'left',
    LeaveLobby = 'leaveLobby',
    DeleteGame = 'deleteGame',
    Alert = 'alert',
}
